export interface MaterialIconDef {
  name: string;
  category: string;
  tags: string[];
}

export const ICON_CATEGORIES = [
  'Vše',
  'Vývoj',
  'Soubory',
  'Web',
  'Aplikace',
  'Zabezpečení',
  'Komunikace',
  'Akce',
  'Média & Zařízení',
  'Obchod',
  'Navigace & Místa',
] as const;

export const POPULAR_MATERIAL_ICONS: MaterialIconDef[] = [
  // ==========================================
  // Vývoj & Programování
  // ==========================================
  { name: 'code', category: 'Vývoj', tags: ['kod', 'vyvoj', 'programovani', 'dev', 'developer', 'source', 'tag', 'html'] },
  { name: 'terminal', category: 'Vývoj', tags: ['terminal', 'prikazova radka', 'cmd', 'bash', 'powershell', 'cli', 'console', 'shell'] },
  { name: 'data_object', category: 'Vývoj', tags: ['json', 'object', 'data', 'struktura', 'payload', 'promenna'] },
  { name: 'data_array', category: 'Vývoj', tags: ['pole', 'array', 'seznam', 'list', 'vektor'] },
  { name: 'database', category: 'Vývoj', tags: ['databaze', 'db', 'sql', 'server', 'mysql', 'postgres', 'storage', 'data'] },
  { name: 'api', category: 'Vývoj', tags: ['api', 'rest', 'endpoint', 'sluzba', 'service', 'integrace', 'http'] },
  { name: 'bug_report', category: 'Vývoj', tags: ['chyba', 'bug', 'debug', 'oprava', 'issue', 'problem', 'brouk'] },
  { name: 'developer_mode', category: 'Vývoj', tags: ['vyvojar', 'mobil', 'android', 'phone', 'zarizeni', 'debug'] },
  { name: 'integration_instructions', category: 'Vývoj', tags: ['integrace', 'navod', 'dokumentace', 'skript', 'postup'] },
  { name: 'webhook', category: 'Vývoj', tags: ['webhook', 'odkaz', 'notifikace', 'automatizace', 'hook'] },
  { name: 'deployed_code', category: 'Vývoj', tags: ['deploy', 'nasazeni', 'produkce', 'build', 'balicek', 'release'] },
  { name: 'code_blocks', category: 'Vývoj', tags: ['bloky', 'funkce', 'snippet', 'knihovna', 'komponenta'] },
  { name: 'memory', category: 'Vývoj', tags: ['pamet', 'ram', 'procesor', 'hardware', 'cpu', 'cip'] },
  { name: 'lan', category: 'Vývoj', tags: ['sit', 'network', 'lokalni', 'server', 'ip', 'ethernet'] },
  { name: 'dns', category: 'Vývoj', tags: ['dns', 'domena', 'server', 'hosting', 'cluster', 'ip'] },
  { name: 'schema', category: 'Vývoj', tags: ['schema', 'diagram', 'struktura', 'relace', 'architektura'] },
  { name: 'data_table', category: 'Vývoj', tags: ['tabulka', 'grid', 'zaznamy', 'sloupce', 'radky'] },
  { name: 'query_stats', category: 'Vývoj', tags: ['dotaz', 'query', 'vykon', 'statistika', 'metriky'] },
  { name: 'sync_saved_locally', category: 'Vývoj', tags: ['git', 'commit', 'lokalni', 'vetev', 'stash'] },
  { name: 'dataset', category: 'Vývoj', tags: ['dataset', 'mnozina', 'kolekce', 'data'] },
  { name: 'view_cozy', category: 'Vývoj', tags: ['zobrazeni', 'grid', 'rozlozeni', 'layout'] },
  { name: 'conversion_path', category: 'Vývoj', tags: ['vetev', 'branch', 'git', 'cesta', 'strom'] },
  { name: 'fork_right', category: 'Vývoj', tags: ['fork', 'vetveni', 'odbocka', 'git'] },
  { name: 'call_split', category: 'Vývoj', tags: ['split', 'rozdelit', 'vetev', 'branch'] },
  { name: 'merge', category: 'Vývoj', tags: ['merge', 'sloucit', 'spojit', 'git'] },
  { name: 'commit', category: 'Vývoj', tags: ['commit', 'verze', 'revize', 'zmena'] },
  { name: 'package_2', category: 'Vývoj', tags: ['balicek', 'npm', 'nuget', 'knihovna', 'modul'] },
  { name: 'extension', category: 'Vývoj', tags: ['rozsireni', 'doplnek', 'plugin', 'extension'] },
  { name: 'smart_toy', category: 'Vývoj', tags: ['robot', 'ai', 'automatizace', 'bot', 'skript'] },

  // ==========================================
  // Soubory & Složky
  // ==========================================
  { name: 'folder', category: 'Soubory', tags: ['slozka', 'adresar', 'dir', 'directory', 'folder'] },
  { name: 'folder_open', category: 'Soubory', tags: ['otevrena slozka', 'adresar', 'prochazet', 'cesta'] },
  { name: 'folder_code', category: 'Soubory', tags: ['repozitar', 'git', 'kod ve slozce', 'projekt'] },
  { name: 'folder_zip', category: 'Soubory', tags: ['zip', 'archiv', 'rar', 'zaloha', 'komprese', 'tar'] },
  { name: 'folder_shared', category: 'Soubory', tags: ['sdilena slozka', 'tym', 'sitovy disk', 'sdileni'] },
  { name: 'create_new_folder', category: 'Soubory', tags: ['nova slozka', 'vytvorit slozku', 'adresar'] },
  { name: 'description', category: 'Soubory', tags: ['soubor', 'dokument', 'text', 'doc', 'file'] },
  { name: 'article', category: 'Soubory', tags: ['clanek', 'zapis', 'text', 'dokument', 'post', 'blog'] },
  { name: 'text_snippet', category: 'Soubory', tags: ['snippet', 'vyrez', 'poznamka', 'text', 'sablonka'] },
  { name: 'file_copy', category: 'Soubory', tags: ['kopie', 'duplikovat', 'soubor', 'dokument'] },
  { name: 'save', category: 'Soubory', tags: ['ulozit', 'disk', 'disketa', 'save'] },
  { name: 'save_as', category: 'Soubory', tags: ['ulozit jako', 'export', 'prejmenovat'] },
  { name: 'download', category: 'Soubory', tags: ['stahnout', 'export', 'ulozeni', 'download'] },
  { name: 'upload', category: 'Soubory', tags: ['nahrat', 'import', 'upload', 'cloud'] },
  { name: 'attach_file', category: 'Soubory', tags: ['priloha', 'sponka', 'spojit', 'odkaz'] },
  { name: 'note_add', category: 'Soubory', tags: ['nova poznamka', 'novy dokument', 'pridat'] },
  { name: 'post_add', category: 'Soubory', tags: ['novy prispevek', 'vlozit clanek'] },
  { name: 'draft', category: 'Soubory', tags: ['koncept', 'rozepsano', 'navrh', 'draft'] },
  { name: 'inventory_2', category: 'Soubory', tags: ['archiv', 'krabice', 'sklad', 'baleni', 'zaloha'] },
  { name: 'drive_file_move', category: 'Soubory', tags: ['presunout soubor', 'premistit'] },
  { name: 'file_present', category: 'Soubory', tags: ['existujici soubor', 'nahrany soubor'] },
  { name: 'snippet_folder', category: 'Soubory', tags: ['slozka snippetu', 'sablonky'] },
  { name: 'source_notes', category: 'Soubory', tags: ['zdrojove poznamky', 'zapisnik'] },
  { name: 'history_edu', category: 'Soubory', tags: ['dokumentace', 'kronika', 'historie souboru'] },

  // ==========================================
  // Web & Sítě
  // ==========================================
  { name: 'public', category: 'Web', tags: ['web', 'svet', 'internet', 'globalni', 'www', 'online'] },
  { name: 'language', category: 'Web', tags: ['jazyk', 'web', 'zemekoule', 'preklad', 'mezinarodni', 'lokalizace'] },
  { name: 'link', category: 'Web', tags: ['odkaz', 'url', 'adresa', 'retezec', 'link'] },
  { name: 'link_off', category: 'Web', tags: ['rozpojit odkaz', 'bez odkazu'] },
  { name: 'open_in_new', category: 'Web', tags: ['otevrit v novem okne', 'externi', 'prohlizec', 'web', 'zalozka'] },
  { name: 'open_in_browser', category: 'Web', tags: ['otevrit v prohlizeci', 'browser', 'chrome', 'edge', 'firefox'] },
  { name: 'cloud', category: 'Web', tags: ['cloud', 'uloziste', 'server', 'online', 'disk'] },
  { name: 'cloud_download', category: 'Web', tags: ['stahnout z cloudu', 'sync'] },
  { name: 'cloud_upload', category: 'Web', tags: ['nahrat do cloudu', 'zaloha'] },
  { name: 'cloud_done', category: 'Web', tags: ['cloud hotovo', 'synchronizovano'] },
  { name: 'cloud_sync', category: 'Web', tags: ['synchronizace cloudu'] },
  { name: 'http', category: 'Web', tags: ['http', 'https', 'protokol', 'web', 'prohlizeni'] },
  { name: 'wifi', category: 'Web', tags: ['wifi', 'pripojeni', 'bezdrat', 'internet', 'sit'] },
  { name: 'wifi_off', category: 'Web', tags: ['offline', 'bez wifi', 'odpojeno'] },
  { name: 'bookmark', category: 'Web', tags: ['zalozka', 'oblibene', 'save', 'pripichnout'] },
  { name: 'bookmarks', category: 'Web', tags: ['vice zalozek', 'kolekce', 'seznam oblibenych'] },
  { name: 'travel_explore', category: 'Web', tags: ['vyhledavac', 'pruzkum', 'google', 'hledani'] },
  { name: 'explore', category: 'Web', tags: ['kompas', 'prozkoumat', 'pruzkumnik'] },
  { name: 'share', category: 'Web', tags: ['sdilet', 'odkaz', 'poslat', 'share'] },
  { name: 'rss_feed', category: 'Web', tags: ['rss', 'novinky', 'feed', 'odber'] },
  { name: 'hub', category: 'Web', tags: ['rozcestnik', 'rozbocovac', 'sit', 'hub'] },
  { name: 'vpn_key', category: 'Web', tags: ['vpn', 'klic', 'pristup', 'tunel'] },

  // ==========================================
  // Nástroje & Aplikace
  // ==========================================
  { name: 'apps', category: 'Aplikace', tags: ['aplikace', 'programy', 'menu', 'mrizka', 'nastroje'] },
  { name: 'settings', category: 'Aplikace', tags: ['nastaveni', 'ozubene kolo', 'preference', 'konfigurace', 'options'] },
  { name: 'settings_suggest', category: 'Aplikace', tags: ['doporucene nastaveni', 'chytre nastaveni'] },
  { name: 'build', category: 'Aplikace', tags: ['nastroj', 'klic', 'oprava', 'konfigurace', 'servis'] },
  { name: 'construction', category: 'Aplikace', tags: ['stavba', 'kladivo', 'oprava', 'prace'] },
  { name: 'tune', category: 'Aplikace', tags: ['ladeni', 'posuvniky', 'filtry', 'mapovani', 'nastaveni'] },
  { name: 'calculate', category: 'Aplikace', tags: ['kalkulacka', 'vypocet', 'matematika', 'suma', 'cisla'] },
  { name: 'search', category: 'Aplikace', tags: ['hledat', 'lupa', 'vyhledavani', 'najit'] },
  { name: 'search_check', category: 'Aplikace', tags: ['overit hledani', 'zkontrolovano'] },
  { name: 'find_in_page', category: 'Aplikace', tags: ['hledat na strance', 'dokument'] },
  { name: 'visibility', category: 'Aplikace', tags: ['nahled', 'oko', 'zobrazit', 'videt'] },
  { name: 'visibility_off', category: 'Aplikace', tags: ['skryt', 'neviditelny', 'tajne'] },
  { name: 'history', category: 'Aplikace', tags: ['historie', 'cas', 'zpet', 'log', 'protokol'] },
  { name: 'schedule', category: 'Aplikace', tags: ['hodiny', 'cas', 'planovac', 'termin', 'budik'] },
  { name: 'timer', category: 'Aplikace', tags: ['stopky', 'odpocet', 'mereni', 'cas'] },
  { name: 'hourglass_top', category: 'Aplikace', tags: ['presypaci hodiny', 'cekani', 'odpocet'] },
  { name: 'alarm', category: 'Aplikace', tags: ['budik', 'upozorneni', 'alarm', 'cas'] },
  { name: 'calendar_month', category: 'Aplikace', tags: ['kalendar', 'mesic', 'datum', 'plan'] },
  { name: 'calendar_today', category: 'Aplikace', tags: ['dnesni datum', 'kalendar', 'den'] },
  { name: 'event', category: 'Aplikace', tags: ['udalost', 'schuzka', 'akce', 'termin'] },
  { name: 'pending_actions', category: 'Aplikace', tags: ['cekajici ukoly', 'fronta', 'todolist'] },
  { name: 'task_alt', category: 'Aplikace', tags: ['splneny ukol', 'hotovo', 'fajfka'] },
  { name: 'palette', category: 'Aplikace', tags: ['paleta', 'barva', 'motiv', 'design', 'vzhled'] },
  { name: 'brush', category: 'Aplikace', tags: ['stetec', 'kresleni', 'malovat', 'grafika'] },
  { name: 'auto_awesome', category: 'Aplikace', tags: ['hvezdicky', 'chytre', 'ai', 'kouzlo', 'vylepseni', 'gemini'] },
  { name: 'auto_fix_high', category: 'Aplikace', tags: ['automaticka oprava', 'kouzelna hulka'] },
  { name: 'widgets', category: 'Aplikace', tags: ['widgety', 'komponenty', 'dlazdice'] },
  { name: 'dashboard', category: 'Aplikace', tags: ['nastenka', 'prehled', 'dashboard', 'panel'] },
  { name: 'speed', category: 'Aplikace', tags: ['rychlost', 'tachometr', 'vykon', 'benchmark'] },
  { name: 'monitoring', category: 'Aplikace', tags: ['monitoring', 'dohled', 'grafy', 'statistika'] },
  { name: 'notifications', category: 'Aplikace', tags: ['oznameni', 'notifikace', 'zvonek', 'upozorneni'] },
  { name: 'notifications_active', category: 'Aplikace', tags: ['aktivni zvonek', 'upozorneni'] },
  { name: 'power_settings_new', category: 'Aplikace', tags: ['vypnout', 'restartovat', 'napajeni', 'power'] },

  // ==========================================
  // Bezpečnost & Přístup
  // ==========================================
  { name: 'lock', category: 'Zabezpečení', tags: ['zamek', 'heslo', 'zabezpeceni', 'soukromi', 'private'] },
  { name: 'lock_open', category: 'Zabezpečení', tags: ['odemceno', 'verejne', 'pristup'] },
  { name: 'key', category: 'Zabezpečení', tags: ['klic', 'token', 'heslo', 'overeni', 'auth'] },
  { name: 'security', category: 'Zabezpečení', tags: ['stit', 'bezpecnost', 'ochrana', 'antivirus', 'magicgate'] },
  { name: 'verified_user', category: 'Zabezpečení', tags: ['overeny', 'certifikat', 'bezpecny', 'schvaleno'] },
  { name: 'admin_panel_settings', category: 'Zabezpečení', tags: ['admin', 'spravce', 'panel', 'opravneni'] },
  { name: 'shield', category: 'Zabezpečení', tags: ['stit', 'ochrana', 'bezpeci'] },
  { name: 'shield_person', category: 'Zabezpečení', tags: ['ochrana uzivatele', 'osobni bezpeci'] },
  { name: 'fingerprint', category: 'Zabezpečení', tags: ['otisk', 'biometrika', 'identita', 'prihlaseni'] },
  { name: 'password', category: 'Zabezpečení', tags: ['heslo', 'pin', 'klic', 'hvezdicky'] },
  { name: 'encrypted', category: 'Zabezpečení', tags: ['sifrovani', 'kryptografie', 'kodovani'] },
  { name: 'badge', category: 'Zabezpečení', tags: ['prukaz', 'ico', 'id', 'zamestnanec', 'profil'] },
  { name: 'policy', category: 'Zabezpečení', tags: ['podminky', 'pravidla', 'licence', 'gdpr'] },
  { name: 'privacy_tip', category: 'Zabezpečení', tags: ['soukromi', 'tip', 'bezpecnost'] },
  { name: 'verified', category: 'Zabezpečení', tags: ['overeno', 'odznak', 'oficialni'] },

  // ==========================================
  // Komunikace & Lidé
  // ==========================================
  { name: 'mail', category: 'Komunikace', tags: ['email', 'posta', 'zprava', 'dopis', 'gmail'] },
  { name: 'mark_email_read', category: 'Komunikace', tags: ['precteny email', 'posta'] },
  { name: 'send', category: 'Komunikace', tags: ['odeslat', 'sipka', 'zprava', 'letadlo', 'poslat'] },
  { name: 'chat', category: 'Komunikace', tags: ['chat', 'bublina', 'komunikace', 'diskuze'] },
  { name: 'chat_bubble', category: 'Komunikace', tags: ['bublina', 'komentar', 'zprava'] },
  { name: 'forum', category: 'Komunikace', tags: ['forum', 'diskuze', 'zpravy', 'komunita'] },
  { name: 'comment', category: 'Komunikace', tags: ['komentar', 'poznamka', 'reakce'] },
  { name: 'support_agent', category: 'Komunikace', tags: ['podpora', 'helpdesk', 'mlog', 'servis', 'sluchatka'] },
  { name: 'person', category: 'Komunikace', tags: ['osoba', 'uzivatel', 'profil', 'jmeno', 'panacek', 'user'] },
  { name: 'person_add', category: 'Komunikace', tags: ['pridat uzivatele', 'novy kontakt'] },
  { name: 'group', category: 'Komunikace', tags: ['skupina', 'tym', 'lide', 'organizace'] },
  { name: 'groups', category: 'Komunikace', tags: ['komunita', 'organizace', 'tymy'] },
  { name: 'contacts', category: 'Komunikace', tags: ['kontakty', 'adresar', 'telefonni seznam'] },
  { name: 'call', category: 'Komunikace', tags: ['telefon', 'mobil', 'volat', 'kontakt', 'hovor'] },
  { name: 'phone', category: 'Komunikace', tags: ['telefon', 'sluchatko', 'volani'] },
  { name: 'contact_phone', category: 'Komunikace', tags: ['vizitka s telefonem', 'kontakt'] },
  { name: 'contact_mail', category: 'Komunikace', tags: ['vizitka s emailem', 'adresa'] },
  { name: 'alternate_email', category: 'Komunikace', tags: ['zavinac', 'email', 'handle', 'username'] },
  { name: 'message', category: 'Komunikace', tags: ['sms', 'zprava', 'upozorneni'] },
  { name: 'campaign', category: 'Komunikace', tags: ['oznameni', 'megafon', 'kampan', 'hlaseni'] },
  { name: 'draw', category: 'Komunikace', tags: ['podpis', 'kreslit', 'rukopis', 'pero'] },

  // ==========================================
  // Akce, Navigace & Stav
  // ==========================================
  { name: 'bolt', category: 'Akce', tags: ['blesk', 'akce', 'rychle', 'spustit', 'energie'] },
  { name: 'play_arrow', category: 'Akce', tags: ['spustit', 'prehrat', 'start', 'run'] },
  { name: 'pause', category: 'Akce', tags: ['pauza', 'pozastavit'] },
  { name: 'stop', category: 'Akce', tags: ['zastavit', 'konec'] },
  { name: 'restart_alt', category: 'Akce', tags: ['restart', 'obnovit', 'znovu', 'refresh'] },
  { name: 'sync', category: 'Akce', tags: ['synchronizace', 'obnovit', 'aktualizovat', 'reload'] },
  { name: 'refresh', category: 'Akce', tags: ['znovu nacist', 'refresh', 'obnovit'] },
  { name: 'check', category: 'Akce', tags: ['fajfka', 'hotovo', 'ano', 'splneno'] },
  { name: 'check_circle', category: 'Akce', tags: ['hotovo', 'uspech', 'fajfka', 'ok', 'valid'] },
  { name: 'done_all', category: 'Akce', tags: ['vse hotovo', 'dve fajfky', 'precteno'] },
  { name: 'error', category: 'Akce', tags: ['chyba', 'varovani', 'stop', 'problem', 'vykricnik'] },
  { name: 'warning', category: 'Akce', tags: ['upozorneni', 'varovani', 'trojuhelnik', 'pozor'] },
  { name: 'info', category: 'Akce', tags: ['informace', 'info', 'napoveda', 'detail'] },
  { name: 'help', category: 'Akce', tags: ['otaznik', 'pomoc', 'napoveda', 'navod'] },
  { name: 'help_outline', category: 'Akce', tags: ['otaznik v krouzku', 'podpora'] },
  { name: 'star', category: 'Akce', tags: ['hvezda', 'oblibene', 'hodnoceni', 'dulezite'] },
  { name: 'star_border', category: 'Akce', tags: ['obrys hvezdy', 'ohodnotit'] },
  { name: 'favorite', category: 'Akce', tags: ['srdce', 'oblibene', 'laska', 'like'] },
  { name: 'content_copy', category: 'Akce', tags: ['kopirovat', 'schranka', 'clipboard', 'copy'] },
  { name: 'content_paste', category: 'Akce', tags: ['vlozit', 'schranka', 'paste'] },
  { name: 'delete', category: 'Akce', tags: ['smazat', 'kos', 'odstranit', 'vymazat'] },
  { name: 'delete_forever', category: 'Akce', tags: ['trvale smazat', 'vysypat kos'] },
  { name: 'edit', category: 'Akce', tags: ['upravit', 'tuzka', 'editovat', 'zmenit'] },
  { name: 'edit_note', category: 'Akce', tags: ['upravit text', 'editace poznamky'] },
  { name: 'add', category: 'Akce', tags: ['pridat', 'plus', 'vytvorit', 'novy'] },
  { name: 'add_circle', category: 'Akce', tags: ['plus v krouzku', 'pridat'] },
  { name: 'remove', category: 'Akce', tags: ['minus', 'odebrat', 'odstranit'] },
  { name: 'close', category: 'Akce', tags: ['zavrit', 'krizek', 'zrusit'] },
  { name: 'cancel', category: 'Akce', tags: ['zrusit', 'storno', 'stop'] },
  { name: 'arrow_forward', category: 'Akce', tags: ['sipka dopredu', 'dalsi', 'open'] },
  { name: 'arrow_back', category: 'Akce', tags: ['sipka zpet', 'predchozi'] },
  { name: 'arrow_upward', category: 'Akce', tags: ['sipka nahoru', 'zvysit'] },
  { name: 'arrow_downward', category: 'Akce', tags: ['sipka dolu', 'snizit'] },
  { name: 'chevron_right', category: 'Akce', tags: ['sipka vpravo', 'rozbalit'] },
  { name: 'chevron_left', category: 'Akce', tags: ['sipka vlevo'] },
  { name: 'expand_more', category: 'Akce', tags: ['rozbalit dolu', 'dropdown'] },
  { name: 'expand_less', category: 'Akce', tags: ['sbalit nahoru'] },
  { name: 'sort', category: 'Akce', tags: ['seradit', 'razeni', 'poradi'] },
  { name: 'filter_alt', category: 'Akce', tags: ['filtr', 'filtrovat', 'trychtyr'] },
  { name: 'more_vert', category: 'Akce', tags: ['tri tecky svisle', 'menu', 'dalsi volby'] },
  { name: 'more_horiz', category: 'Akce', tags: ['tri tecky vodorovne', 'moznosti'] },
  { name: 'touch_app', category: 'Akce', tags: ['kliknout', 'dotyk', 'prst', 'tlacitko'] },
  { name: 'undo', category: 'Akce', tags: ['zpet', 'odvolat'] },
  { name: 'redo', category: 'Akce', tags: ['znovu', 'vpred'] },
  { name: 'push_pin', category: 'Akce', tags: ['pripichnout', 'spendlik', 'pripnout'] },

  // ==========================================
  // Média & Zařízení
  // ==========================================
  { name: 'desktop_windows', category: 'Média & Zařízení', tags: ['pocitac', 'monitor', 'windows', 'obrazovka', 'pc'] },
  { name: 'laptop', category: 'Média & Zařízení', tags: ['notebook', 'laptop', 'pocitac', 'prenosny'] },
  { name: 'smartphone', category: 'Média & Zařízení', tags: ['mobil', 'telefon', 'smartphone', 'android', 'ios'] },
  { name: 'tablet', category: 'Média & Zařízení', tags: ['tablet', 'ipad', 'obrazovka'] },
  { name: 'keyboard', category: 'Média & Zařízení', tags: ['klavesnice', 'zkratka', 'psani'] },
  { name: 'mouse', category: 'Média & Zařízení', tags: ['mys', 'kurzor', 'klik'] },
  { name: 'print', category: 'Média & Zařízení', tags: ['tiskarna', 'tisk', 'tlacenka'] },
  { name: 'headphones', category: 'Média & Zařízení', tags: ['sluchatka', 'zvuk', 'poslech'] },
  { name: 'headset', category: 'Média & Zařízení', tags: ['headset', 'sluchatka s mikrofonem', 'call'] },
  { name: 'mic', category: 'Média & Zařízení', tags: ['mikrofon', 'zvuk', 'nahravani'] },
  { name: 'mic_off', category: 'Média & Zařízení', tags: ['ztlumit mikrofon', 'mute'] },
  { name: 'volume_up', category: 'Média & Zařízení', tags: ['zvuk', 'audio', 'reproduktor', 'hlasitost'] },
  { name: 'volume_off', category: 'Média & Zařízení', tags: ['ztlumit', 'mute', 'ticho'] },
  { name: 'image', category: 'Média & Zařízení', tags: ['obrazek', 'fotka', 'foto', 'obraz', 'grafika', 'png', 'jpg'] },
  { name: 'photo_camera', category: 'Média & Zařízení', tags: ['fotoaparat', 'kamera', 'snimek'] },
  { name: 'videocam', category: 'Média & Zařízení', tags: ['video', 'kamera', 'film', 'zaznam', 'meeting'] },
  { name: 'movie', category: 'Média & Zařízení', tags: ['film', 'video', 'kino'] },
  { name: 'music_note', category: 'Média & Zařízení', tags: ['hudba', 'nota', 'pisnicka'] },
  { name: 'tv', category: 'Média & Zařízení', tags: ['televize', 'obrazovka', 'displej'] },
  { name: 'cast', category: 'Média & Zařízení', tags: ['odeslat obrazovku', 'chromecast', 'stream'] },
  { name: 'bluetooth', category: 'Média & Zařízení', tags: ['bluetooth', 'bezdrat', 'parovani'] },
  { name: 'qr_code', category: 'Média & Zařízení', tags: ['qr kod', 'skenovat', 'kod'] },

  // ==========================================
  // Obchod & Finance
  // ==========================================
  { name: 'shopping_cart', category: 'Obchod', tags: ['kosik', 'nakup', 'eshop', 'objednavka'] },
  { name: 'add_shopping_cart', category: 'Obchod', tags: ['pridat do kosiku', 'nakoupit'] },
  { name: 'shopping_bag', category: 'Obchod', tags: ['taska', 'nakupy', 'balicek'] },
  { name: 'store', category: 'Obchod', tags: ['obchod', 'prodejna', 'shop', 'kram'] },
  { name: 'storefront', category: 'Obchod', tags: ['vyloha', 'prodejna', 'obchod'] },
  { name: 'receipt', category: 'Obchod', tags: ['faktura', 'uctenka', 'doklad', 'dph', 'ico'] },
  { name: 'receipt_long', category: 'Obchod', tags: ['dlouha uctenka', 'danovy doklad', 'dic'] },
  { name: 'payments', category: 'Obchod', tags: ['platba', 'penize', 'mena', 'bankovky', 'karta'] },
  { name: 'payment', category: 'Obchod', tags: ['platba', 'kartou', 'online'] },
  { name: 'account_balance', category: 'Obchod', tags: ['banka', 'ucet', 'instituce', 'financni', 'iban'] },
  { name: 'account_balance_wallet', category: 'Obchod', tags: ['penezenka', 'finance', 'kredit'] },
  { name: 'credit_card', category: 'Obchod', tags: ['kreditni karta', 'platba', 'karta', 'debetka'] },
  { name: 'savings', category: 'Obchod', tags: ['prasatko', 'uspory', 'setrit', 'investice'] },
  { name: 'sell', category: 'Obchod', tags: ['prodej', 'stitek', 'stitky', 'cena'] },
  { name: 'local_offer', category: 'Obchod', tags: ['sleva', 'akce', 'stitek', 'nabidka'] },
  { name: 'loyalty', category: 'Obchod', tags: ['vernost', 'bonus', 'body'] },
  { name: 'percent', category: 'Obchod', tags: ['procento', 'sleva', 'dph', 'urok'] },
  { name: 'point_of_sale', category: 'Obchod', tags: ['pokladna', 'pos terminal'] },
  { name: 'monetization_on', category: 'Obchod', tags: ['mince', 'penize', 'zisk'] },
  { name: 'currency_exchange', category: 'Obchod', tags: ['smenarna', 'mena', 'kurz'] },
  { name: 'analytics', category: 'Obchod', tags: ['graf', 'statistika', 'analyza', 'report', 'metriky'] },
  { name: 'trending_up', category: 'Obchod', tags: ['rust', 'trend', 'graf', 'vysledky', 'nahoru'] },
  { name: 'trending_down', category: 'Obchod', tags: ['pokles', 'dolu', 'ztrata'] },
  { name: 'pie_chart', category: 'Obchod', tags: ['kolacovy graf', 'diagram', 'podil', 'data'] },
  { name: 'bar_chart', category: 'Obchod', tags: ['sloupcovy graf', 'metriky', 'statistika'] },
  { name: 'show_chart', category: 'Obchod', tags: ['liniovy graf', 'krivka', 'trend'] },
  { name: 'price_check', category: 'Obchod', tags: ['kontrola ceny', 'overeni'] },

  // ==========================================
  // Navigace & Místa
  // ==========================================
  { name: 'home', category: 'Navigace & Místa', tags: ['domov', 'domu', 'hlavni stranka', 'homepage'] },
  { name: 'home_pin', category: 'Navigace & Místa', tags: ['domaci adresa', 'bydliste', 'adresa'] },
  { name: 'work', category: 'Navigace & Místa', tags: ['prace', 'zamestnani', 'kufrik', 'byznys'] },
  { name: 'place', category: 'Navigace & Místa', tags: ['misto', 'lokace', 'adresa', 'mapa', 'bod'] },
  { name: 'location_on', category: 'Navigace & Místa', tags: ['lokace', 'gps', 'pozice', 'adresa'] },
  { name: 'my_location', category: 'Navigace & Místa', tags: ['moje poloha', 'zamerit gps'] },
  { name: 'map', category: 'Navigace & Místa', tags: ['mapa', 'orientace', 'trasa'] },
  { name: 'navigation', category: 'Navigace & Místa', tags: ['navigace', 'smer', 'sipka'] },
  { name: 'directions', category: 'Navigace & Místa', tags: ['navigovat', 'cesta', 'trasa'] },
  { name: 'business', category: 'Navigace & Místa', tags: ['budova', 'firma', 'spolecnost', 'sidlo'] },
  { name: 'apartment', category: 'Navigace & Místa', tags: ['kancelare', 'panelak', 'byty'] },
  { name: 'factory', category: 'Navigace & Místa', tags: ['tovarna', 'vyroba', 'prumysl'] },
  { name: 'domain', category: 'Navigace & Místa', tags: ['domena', 'instituce', 'budovy'] },
  { name: 'local_shipping', category: 'Navigace & Místa', tags: ['doprava', 'dodavka', 'kuryr', 'zasilka', 'nakladak'] },
  { name: 'flight', category: 'Navigace & Místa', tags: ['letadlo', 'letenka', 'cesta', 'letiste'] },
  { name: 'train', category: 'Navigace & Místa', tags: ['vlak', 'nadrazi', 'cesta'] },
  { name: 'commute', category: 'Navigace & Místa', tags: ['dojizdeni', 'auto', 'verejna doprava'] },
  { name: 'directions_car', category: 'Navigace & Místa', tags: ['auto', 'vozidlo', 'ridic'] },
  { name: 'near_me', category: 'Navigace & Místa', tags: ['pobliz', 'okoli', 'blizko'] },
];
