export interface VersionEntry {
  version: string;
  date: string;
  title: string;
  highlights: string[];
}

export const CURRENT_APP_VERSION = '1.1.24';

/**
 * Uživatelsky přívětivá historie verzí (ne technický žargon, ale přehled reálných funkcí pro uživatele).
 */
export const CHANGELOG_HISTORY: VersionEntry[] = [
  {
    version: '1.1.24',
    date: '24. 9. 2026',
    title: 'ScreenRuler zrušení výběru a spolehlivé notifikace schránky, QuickCap zkratka P a vyladění kapátka',
    highlights: [
      'ScreenRuler – Zrušení výběru přes ESC: První stisk klávesy Esc při aktivním obdélníkovém výběru zruší pouze rozpracovaný výběr bez uzavření pravítka, další stisk Esc pravítko zavře.',
      'Spolehlivé nativní notifikace při kopírování: Zkopírování naměřených rozměrů (klikem na bar i klávesou C) spolehlivě zobrazí Windows toast banner; odstraněn systémový stav QUNS_BUSY, který toastové notifikace ve Windows potlačoval.',
      'Vyladění nástrojové lišty ScreenRuleru: V přepínači režimů nasazena ikona crop_free pro obdélníkový výběr, odstraněna redundantní ikona klávesnice u lišty zkratek a nastaveno pevné neprůhledné grafitové pozadí bez nežádoucího průhledu.',
      'QuickCap – Okamžitý snímek celé obrazovky zkratkou P: Přidáno tlačítko „Vyfotit celou obrazovku“ s klávesovou zkratkou P v bublině pro pořízení kompletního screenshotu jedním stiskem.',
      'QuickCap – Reset tažení výběru přes ESC: Stisk klávesy Esc během tažení myší zruší aktuální výběr a umožní ihned provést nový výběr bez nutnosti restartu nástroje.',
      'Plynulé přechody mezi nástroji bez problikávání: Odstraněny černé a bílé záblesky při rychlém střídání QuickCapu a ScreenRuleru díky přednačtení snímků obrazovky a vzájemnému korektnímu uzavírání oken.',
      'Kapátko (ColorMaster) – Dokonale ostrý vnější rámeček: Odstraněn rámeček z vnitřního okénka lupy, opraveno oříznutí vnějšího rámečku celého plovoucího okna v GDI a sjednoceny texty zkratek na malá písmena.',
      'Nastavení – Zobecnění notifikací schránky: Popisek volby „Kopírování do schránky“ v Nastavení byl rozšířen a zobecněn pro všechny nástroje (Spotlight, ScreenRuler apod.).',
    ],
  },
  {
    version: '1.1.23',
    date: '24. 9. 2026',
    title: 'ScreenRuler pravítko, nativní Windows notifikace a vizuální sjednocení DonkeyTools se Spotlightem',
    highlights: [
      'ScreenRuler (Měřítko a pravítko obrazovky) v DonkeyTools: Nové rozšíření pro přesné měření na obrazovce v obdélníkovém režimu (šířka, výška, poměr stran, plocha px²) a celoobrazovkovém režimu kříže (vzdálenosti ke 4 okrajům monitoru). Podpora jednotek px, % i dp, klávesové zkratky a rychlé vyvolání příkazy /ruler, /pravitko, /meritko, /scale.',
      'Nativní Windows notifikace při kopírování rozměrů: Při zkopírování rozměrů do schránky se namísto interního toastu na obrazovce spolehlivě zobrazí systémová notifikace Windows a akce je zalogována do Protokolu akcí (Action Log).',
      'Stabilní zobrazení čísel v Ruler baru bez poskakování: Kontejnery čísel mají pevnou šířku pro 4místná čísla (tabular-nums), takže lišta při změně hodnot zůstává naprosto stabilní.',
      'Sjednocení výšek ovládacích prvků v Ruler baru: Všechny komponenty, přepínače a tlačítka nástrojové lišty ScreenRuleru mají striktně sjednocenou výšku h-8 (32 px) a dokonale sedí na jedné lince.',
      'Vizuální sjednocení ScreenRuleru se Spotlightem: Grafitový skleněný podklad bg-[#1c1d24]/90 s backdrop-blur-2xl, zaoblení rounded-2xl s border border-white/10, vnitřní karty rounded-xl a klávesové badgy ve stylu Spotlight <kbd>.',
      'Vizuální sjednocení QuickCap (Crop bar): Horní nápověda přepracována do zaoblené rounded-2xl karty s grafitovým sklem a Spotlight <kbd>Esc</kbd> badgem, štítek rozměrů výstřižku v moderním rounded-xl skleněném provedení.',
      'Vizuální sjednocení Kapátka (ColorMaster): Nativní Windows okno lupy má fyzicky zaoblené rohy (rounded-2xl / 20 px rádius), grafitové pozadí #1c1d24, zaoblenou vnitřní mřížku pixelů, Rose zaměřovač a Spotlight kbd badgy pro [Klik] a [Esc].',
      'Dynamické Tray menu a striktní Rose identita (#f43f5e): Nástroje DonkeyTools se v Tray menu zobrazují pouze tehdy, když jsou povolené a aktivní, a celá sada DonkeyTools striktně ctí Rose barvu.',
    ],
  },
  {
    version: '1.1.22',
    date: '23. 9. 2026',
    title: 'Vývojářský režim, nová záložka Systém, přesun chybových protokolů a tray zkratky nástrojů',
    highlights: [
      'Vývojářský a diagnostický režim (isDevelop): Nový skrytý režim odemykaný easter eggem – 10násobným kliknutím na číslo verze v záložce Systém. Zobrazuje počítadlo zbývajících kliknutí, po aktivaci odemkne novou záložku „Vývojář“ v bočním menu a při opakovaném kliknutí upozorní, že režim je již aktivní.',
      'Nová záložka Vývojář v Nastavení: Obsahuje hlavní přepínač pro okamžitou deaktivaci a skrytí režimu, přímé tlačítko pro otevření Chrome DevTools vývojářské konzole, generátor testovacího crashlogu pro ověření diagnostiky a kompletní auditní Protokol prováděných akcí (Action Log).',
      'Trvalý běh nahrávání akcí na pozadí: Služba zaznamenávání akcí běží nepřetržitě na pozadí nezávisle na vývojářském režimu, což zaručuje kompletní časovou osu událostí při každém exportu crashlogu.',
      'Přejmenování záložky Aktualizace na „Systém“: Záložka byla přejmenována na „Systém“ s ikonou systému a přesunem kompletní diagnostiky a správy chybových protokolů (Crashlogs) ze záložky Nápověda.',
      'Duální indikátor na záložce Systém: Tlačítko záložky Systém disponuje dvěma souběžnými indikátory – štítkem nové verze v uživatelsky zvolené primární barvě motivu aplikace a červeným číselným štítkem počtu zachycených chybových protokolů.',
      'Větší výška okna Nastavení (+100 px): Výchozí výška okna Nastavení byla navýšena ze 720 px na 820 px pro komfortnější procházení dlouhých seznamů a konfigurací.',
      'Rychlé vyvolání QuickCap a Kapátka z Tray ikony: Kontextová nabídka ikony v oznamovací oblasti Windows byla rozšířena o přímé akce pro spuštění výstřižku obrazovky a kapátka barev ColorMaster.',
      'Oprava synchronizační notifikace z Traye: Po kliknutí na „Synchronizovat data nyní“ v tray menu se po úspěšném dokončení spolehlivě zobrazí systémová notifikace Windows s počtem načtených záznamů.',
      'Dynamický čip DonkeyTools v záložce Rozšíření: V přehledu rozšíření se pro DonkeyTools zobrazuje zelený stavový štítek s počtem aktivních nástrojů, nebo výrazný červený štítek „Nenakonfigurováno“ v případě nulové konfigurace.',
      'Optimalizace stahování a odstraňování duplicit: Odstraněn duplicitní ukazatel průběhu synchronizace v záložce Zdroje dat a stisk klávesy Enter po dokončení stahování (Git, MagicGate, CMSinFS) otevře cílovou složku v Průzkumníku, zavře dialog a resetuje vyhledávač.',
      'Kompaktnější výška SplashScreenu: Výška úvodní obrazovky byla zmenšena o cca 50 px (na 350 px) pro optimální vycentrování na všech typech displejů.',
    ],
  },
  {
    version: '1.1.21',
    date: '22. 9. 2026',
    title: 'Stažení CMSinFS zdrojáků, dedikované okno stahování a vyladění akcí Spotlightu',
    highlights: [
      'Stažení zdrojových kódů CMSinFS (pro PRG): Nová akce ve Spotlightu u instancí MagicGate s možností nastavení vlastní cílové složky pro stažení obsahu instance.',
      'Dedikované okno stahování CMSinFS: Samostatné modální okno s živým protokolem operací, indikátorem průběhu stahování ZIP archivu, rotujícím spinnerem a tlačítky pro přímé otevření ve VS Code nebo v Průzkumníku Windows.',
      'Vyladění chování stahovacích oken: Po dokončení stahování (GitHub, MagicGate, CMSinFS) klávesa Enter simuluje tlačítko Zavřít; tlačítko Zavřít v patičce okno zavře a resetuje Spotlight bez jeho nežádoucího otevření; tlačítko Otevřít v Průzkumníku nezavírá okno.',
      'Oddělení hoveru myši od klávesového výběru: Přejíždění myší nad výsledky vyhledávání ve Spotlightu již neposouvá scroll okna ani nepřebíjí aktivní výběr klávesnicí.',
      'Přesné označení akce VS Code u MagicGate: U instancí MagicGate se akce jmenuje „Otevřít repozitáře ve VS Code“, zatímco u běžných repozitářů GitHubu zůstává „Otevřít ve VS Code“.',
      'Vyladění akcí ColorMaster a QuickCap: Z nabídky akcí barvy odstraněna nadbytečná akce Zavřít (zavírá se přes Esc) a opravena kolize s cizím štítkem Gmail; u QuickCapu má první akce výstižný popis „Již zkopírováno ve schránce“ a je zvýrazněna červenou stavovou barvou.',
      'Vyvážené rozměry SplashScreenu: Šířka úvodního okna zmenšena o 20 px na 380 px a vnitřní odsazení o 10 px pro čistší proporce.',
      'Zjednodušená nápověda DonkeyTools: Doporučené příkazy pro ColorMaster a QuickCap zjednodušeny na /color a /cap s instrukcemi pro zkratku a tlačítko nástrojů.',
    ],
  },
  {
    version: '1.1.20',
    date: '22. 9. 2026',
    title: 'Nativní systémové notifikace Windows, Photoshop-style SplashScreen a rychlé akce nástrojů',
    highlights: [
      'Nativní systémové notifikace Windows: Plná integrace notifikací Windows s dynamickou registrací AppUserModelId pro QuickCap, ColorMaster, schránku, synchronizaci, aktualizace a zachycené chyby aplikace.',
      'Nastavení notifikací v Nastavení: Globální vypínač, tichý režim bez zvuku Windows, přepínače jednotlivých událostí a dvojice tlačítek pro otestování úspěšné i chybové notifikace.',
      'Akce „Zavřít“ na první pozici: Po dokončení výstřižku (QuickCap) i nabrání barvy (ColorMaster) je na 1. pozici ve Spotlightu zařazena akce Zavřít s okamžitým výběrem pro rychlé zavření stiskem Enter.',
      'Izolace kapátka v Nastavení: Výběr primární/akční barvy v Nastavení nekopíruje barvu do schránky, nevyvolává toast ani neotevírá Spotlight – barva se pouze aplikuje a fokus zůstává v Nastavení.',
      'Plovoucí dialog novinek (Release Notes): Odstraněn ostrý černý podklad, dialog plave čistě se zaoblenými rohy (16px), podkladový vyhledávač je skryt a okno lze zavřít klávesou Escape.',
      'Nový vertikální SplashScreen (Photoshop-style layout): Kompaktní vertikální formát (350 × 400 px) se zarovnáním vlevo, velkou ikonou (58 px), výrazným názvem, obecným popisem a spodním copyrightem © 2026 Petr Coolhanek.',
      'Sjednocení barev ikon a vyladění Nápovědy: Ikony notifikací v Nastavení přebírají primární barvu motivu a text chybových protokolů v Nápovědě byl zobecněn.',
    ],
  },
  {
    version: '1.1.19',
    date: '19. 9. 2026',
    title: 'Subrozšíření QuickCap pro výstřižky obrazovky, správce výstřižků a sjednocený design nástrojů',
    highlights: [
      'Subrozšíření QuickCap (výstřižky obrazovky): Nový vestavěný nástroj v DonkeyTools pro bleskové pořízení výstřižku libovolné části obrazovky.',
      'Celoobrazovkový interaktivní výběr: Výběr obdélníkové oblasti pokrývá celou plochu monitoru včetně lišty Windows se ztmaveným pozadím a živým zobrazením rozměrů v pixelech.',
      'Automatické uložení a vložení do schránky: Pořízený snímek se ihned zkopíruje do schránky pro vložení (Ctrl+V) a uloží jako PNG do složky (výchozí: Obrázky\\IADonkey Screenshots).',
      'Globální klávesová zkratka & příkazy: Volitelná globální klávesová zkratka s interaktivním nahráváním a ochranou proti kolizím. Podpora příkazů ve Spotlightu: /quickcap, /cap, /vystrizek, /snip, /screenshot, /snap.',
      'Správce výstřižků v Nastavení: Možnost volby vlastní cílové složky pro ukládání, přímé tlačítko pro otevření složky v Průzkumníku Windows a galerie posledních 10 výstřižků (náhled, rozměry, datum pořízení, zkopírovat znovu, otevřít v Průzkumníku, smazat).',
      'Plynulé skrytí Spotlightu: Při aktivaci nástrojů (QuickCap, kapátko) se okno Spotlightu plynule animovaně skryje, čímž se zamezí nechtěnému probliknutí při dalším vyvolání.',
      'Sjednocený design ikonek nástrojů: Ikonky aktivních subnástrojů v rozbalovacím menu DonkeyTools ve Spotlightu mají stejné zaoblení (rounded-lg) jako ostatní ovládací prvky.',
      'Výchozí stav subextensions: Jednotlivá subrozšíření v DonkeyTools jsou ve výchozím stavu vypnutá (opt-in) a aplikace spolehlivě pamatuje volbu uživatele.',
    ],
  },
  {
    version: '1.1.18',
    date: '18. 9. 2026',
    title: 'Diagnostický Crashlog systém s exportem časové osy, auditní Action Log a oprava kapátka v Release',
    highlights: [
      'Oprava systémového kapátka v produkčním balíčku: Doplněna konfigurace asarUnpack pro nativní color-picker.exe a záložní automatická extrakce do systémové složky aplikace – kapátko v Release verzi již neproblikává a spolehlivě snímá barvy.',
      'Diagnostický crashlog systém (složka crashlog/): Automatické zachytávání pádů, systémových chyb a neobsloužených výjimek do dedikované složky s detailním časem, kontextem a stack tracem.',
      'Automaticky navázaná časová osa akcí (Action Log Timeline): Každý crashlog v sobě obsahuje chronologický snímek akcí před selháním se zvýrazněním momentu, kdy k chybě došlo.',
      'Export chybových protokolů do souboru (.txt / .log): U každého záznamu v Nápovědě je tlačítko Exportovat pro uložení formátovaného diagnostického balíčku.',
      'Průběžný auditní Action Log: Zaznamenávání provedených uživatelských akcí (výběr položky, otevření nabídky akcí, vstup do podpoložek, spuštění nástrojů, kopírování z infokarty, synchronizace) v 50prvkovém FIFO ring-bufferu.',
      'Nové uspořádání Nápovědy: V záložce Nápověda (Help) je nejprve přehledný Action Log a pod ním Chybové protokoly s možností zobrazení detailu a vyčištění historie.',
      'Ochrana podpoložek před AutoLoginem: Podpoložky (např. Web, API, BO) u instancí IS Tour již nezdědí nastavení magicgate, takže se otevírají okamžitě bez chybného handshake a falešných pádů.',
    ],
  },
  {
    version: '1.1.17',
    date: '17. 9. 2026',
    title: 'Rozšíření DonkeyTools, ColorMaster se systémovým kapátkem, okno doladění barvy a rychlé nástroje ve Spotlightu',
    highlights: [
      'Nové rozšíření DonkeyTools: Sada integrovaných pomocných nástrojů s vínovým motivem a možností centrálního zapnutí či vypnutí.',
      'Rychlé nástroje DonkeyTools ve Spotlightu: Tlačítko nástrojů před aktualizací s vysouvací nabídkou aktivních subextensions (kolečko s kapátkem ColorMaster).',
      'ColorMaster (správa a převod barev): Podpora rozpoznání barevných formátů (#HEX, RGB, RGBA, HSL) přímo ve Spotlightu s živým náhledem barvy, kopírováním (včetně akce pro RGBA) nebo nastavením jako barvy motivu.',
      'Systémové kapátko (EyeDropper): Spolehlivé nabrání barvy odkudkoliv z obrazovky s nativním kurzorem kapátka a zvětšovací lupou přes globální zkratku, nabídku rychlých nástrojů ve Spotlightu, příkazy /kapatko, /picker i přímo z nastavení barev motivu. Po nasátí barvy se automaticky otevře nabídka akcí barvy ve Spotlightu a hodnota se zkopíruje do schránky.',
      'Okno pro doladění barvy: Nová akce „Doladit barvu...“ v nabídce akcí otevře samostatné okno v hlavním panelu Windows s posuvníky složek RGB, průhlednosti a odstínu. Uložením se aplikace vrátí přímo do nabídky akcí k upravené barvě.',
      'Interaktivní nahrávání zkratky kapátka: Nastavení zkratky pro kapátko využívá stejné nahrávání jako launcher, včetně ochrany proti kolizím s launcherem či rezervovanými klávesami s automatickým pozastavením zkratek při nahrávání.',
      'Lomítkové příkazy (/): Spotlight podporuje rychlé systémové příkazy začínající lomítkem s našeptáváním dostupných akcí (/kapatko, /color, /picker, /barva).',
      'Optimalizace rozvržení detailu akcí: Výška seznamu akcí byla upravena tak, aby se spodní okraj karty Spotlightu nikdy neořezával o hranice okna.',
      'Širší obdélníkový Splash Screen: Úvodní obrazovka při startu byla rozšířena na formát 380 × 230 px pro elegantnější a vyváženější proporce.',
      'Dynamická nápověda podle aktivních rozšíření: Seznam klávesových zkratek i karet chytrých funkcí v nápovědě dynamicky reaguje na zapnutí či vypnutí rozšíření DonkeyTools a ColorMaster.',
    ],
  },
  {
    version: '1.1.16',
    date: '17. 9. 2026',
    title: 'Přejmenování na Taskmanager, plynulejší zobrazení položek a dialog správy aplikace',
    highlights: [
      'Přejmenování MLog na Taskmanager: Rozšíření bylo v celé aplikaci přejmenováno na obecný Taskmanager se všemi popisy a ukázkovými doménami (např. company.com).',
      'Vlastní prefixy pro Úkoly a Požadavky: V nastavení Taskmanageru lze libovolně nastavit prefix pro úkoly (výchozí T) i požadavky (výchozí R) s živým náhledem bubliny.',
      'Chytré vyhledávání podle čísla: Při zadání 3 a více číslic (např. 12345) Spotlight automaticky nabídne otevření jak úkolu, tak požadavku.',
      'Okamžité otevření seznamu položek bez zamrzání: Zobrazení načtených položek ve vyhledávání používá progresivní vykreslování – okno i přepínání záložek reaguje okamžitě.',
      'Vizuální indikátor banování: Tlačítka pro vyřazení a obnovení položek z vyhledávání nyní zobrazují točící se spinner během provádění akce.',
      'Dialog pro restart a ukončení: Dlouhým podržením (3 sekundy) ikony ozubeného kolečka ve Spotlightu se otevře okno správy aplikace na hlavním panelu.',
      'Kruhový indikátor průběhu držení nastavení: Při držení tlačítka nastavení se kolem ikony plynule vykresluje gradientní kruhový progress ring a ozubené kolečko se jemně otáčí, dokud se neotevře dialog pro restart a ukončení.',
      'Čistý Splash Screen bez stínů a ohraničení: Odstraněn veškerý stín (box-shadow) i transparentní okraj kolem splash screenu – zobrazuje se čistá zaoblená karta bez jakéhokoliv tmavého oparu či backdropu.',
      'Zachování navigace v podpoložkách: Otevření a zavření nastavení již neruší rozbalené zobrazení subpoložek ve Spotlightu.',
      'Přehlednější nastavení zdrojů: Odstraněn nadbytečný oddělovač a barevně odlišeny štítky FILE, API a Mapováno.',
    ],
  },
  {
    version: '1.1.15',
    date: '17. 9. 2026',
    title: 'Bezrámečkový zaoblený Splash Screen a plynulý reset Spotlightu při kliknutí vedle',
    highlights: [
      'Okamžité zobrazení Splash Screenu bez prodlevy: Splash screen se zobrazí rovnou s kompletním obsahem (ikonou i textem) bez předchozího zobrazení prázdného tmavého okna.',
      'Čistý bezrámečkový design s výraznějším zaoblením: Odstraněn jakýkoliv rámeček, okraj i ohraničení (borderless card) a rohy byly elegantně zaobleny (poloměr 28 px) pro moderní styl.',
      'Plynulé zavírání a reset Spotlightu při kliknutí vedle: Vyřešeno probliknutí při opětovném vyvolání Spotlightu klávesovou zkratkou po předchozím kliknutí mimo okno. Stav skrytí se okamžitě a spolehlivě resetuje.',
      'Optimalizace náběhu procesoru: Skenování aplikací a síťová synchronizace se spouští až s odstupem po otevření Spotlightu, takže start programu je maximálně plynulý.',
    ],
  },
  {
    version: '1.1.14',
    date: '17. 9. 2026',
    title: 'Okamžitý náběh Splash Screenu a synchronizovaný 5s odpočet',
    highlights: [
      'Okamžité zobrazení Splash Screenu: Přechod na nativní neprůhledné Win32 okno s tmavým pozadím #141520 eliminuje vrstvené DWM kompozice a zpoždění. Okno se zobrazí čistě a spolehlivě ihned po spuštění.',
      'Synchronizovaný 5sekundový odpočet: Časovač 5 sekund začíná běžet až ve chvíli, kdy je splash screen skutečně fyzicky vykreslen a viditelný na monitoru. Uživatel má garantováno celých 5 sekund zobrazení bez jakéhokoliv problikávání.',
      'Bleskový start bez přetížení procesoru: Náročné úlohy na pozadí (skenování nainstalovaných aplikací a datová synchronizace) jsou odloženy až po zobrazení úvodní obrazovky, takže nezatěžují CPU při prvním vykreslení.',
      'Plynulé otevření Spotlightu: Po uplynutí 5 sekund a dokončení inicializace se splash screen plynule skryje a vyhledávací okno Spotlight se automaticky zobrazí a získá okamžitý fokus.',
    ],
  },
  {
    version: '1.1.13',
    date: '17. 9. 2026',
    title: 'Spolehlivé zobrazení Splash Screenu v produkci a podpora RDP/virtuálních prostředí',
    highlights: [
      'Spolehlivé zobrazení Splash Screenu v produkčním .exe: Zahrnutí složky electron/assets do produkčního instalačního balíčku asar a vestavění přímé Base64 zálohy ikony zaručuje okamžité vykreslení bez závislosti na diskových cestách.',
      'Plná viditelnost v RDP a softwarovém vykreslování: Splash okno používá plné neprůhledné pozadí #141520 namísto průhledného rámce, díky čemuž se spolehlivě zobrazí i ve vzdálených plochách (RDP) a na strojích bez hardwarové GPU akcelerace.',
      'Garantovaný 5sekundový čas běhu Splash Screenu: Úvodní obrazovka zůstává zobrazená minimálně 5 sekund, aby uživatel vždy zachytil start aplikace.',
      'Automatická aktivace vyhledávání Spotlight: Po uplynutí 5s a dokončení načtení se splash screen plynule skryje a okno Spotlightu se samo zobrazí, vycentruje na aktivním monitoru a okamžitě získá fokus.',
    ],
  },
  {
    version: '1.1.12',
    date: '17. 9. 2026',
    title: 'Okamžité zobrazení Splash Screenu na frame 0 a garantovaný 5s start',
    highlights: [
      'Okamžité zobrazení Splash Screenu (Frame 0): okno je vykresleno přímo z paměti pomocí samostatného odlehčeného HTML namísto čekání na objemný React bundle. Zobrazí se bleskově během 2 ms.',
      'Garantovaný 5sekundový čas běhu: splash screen zůstává zobrazen po dobu minimálně 5 sekund, aby uživatel jasně viděl, že aplikace startuje.',
      'Plynulá aktivace Spotlightu: po uplynutí 5 sekund a ověření připravenosti se splash okno plynule zavře a Spotlight automaticky vyskočí s aktivním fokusem.',
    ],
  },
  {
    version: '1.1.11',
    date: '16. 9. 2026',
    title: 'Photoshop-style čtvercový Splash Screen a automatická aktivace Spotlightu',
    highlights: [
      'Čistý čtvercový Splash Screen ve stylu Photoshopu: minimalistické tmavé čtvercové okno (260x260 px) se zaoblenými rohy, dominantní 48px ikonou maskota IADonkey uprostřed, názvem aplikace a štítkem verze.',
      'Garantovaný 5sekundový čas zobrazení: splash screen běží minimálně 5 sekund, takže si uživatel stihne všimnout spuštění aplikace. Pokud načítání trvá déle, splash počká na skutečné dokončení.',
      'Automatická aktivace Spotlightu po startu: jakmile uplyne 5s a aplikace je plně načtena v paměti, splash plynule zmizí a Spotlight se automaticky zobrazí, vycentruje na monitoru s myší a získá okamžitý fokus pro psaní dotazu.',
      'Tichý start se systémem Windows: při spuštění na pozadí s Windows (--background, --silent) se splash nezobrazuje a Spotlight zůstává skrytý v oznamovací oblasti.',
    ],
  },
  {
    version: '1.1.10',
    date: '16. 9. 2026',
    title: '100% tichý restart po aktualizaci a nový Startup Splash Screen',
    highlights: [
      '100% tichý In-App restart bez probliknutí okna příkazové řádky: spuštění výměnného skriptu nově obstarává Windows Script Host (wscript.exe / .vbs) v GUI subsystému s příznakem SW_HIDE. Při restartu po aktualizaci již nikdy nedojde k alokaci ani probliknutí černé konzole cmd.exe.',
      'Nový Startup Splash Screen: při spuštění aplikace (i po dokončení aktualizace) se zobrazí kompaktní elegantní mini-okno ve stylu IADonkey s oficiální ikonou maskota, verzí programu a indikátorem průběhu startu.',
      'Živá indikace fází spouštění: plynulý indigovo-fialový progress bar a stavový text informují o fázích inicializace (načítání konfigurace, registrace klávesové zkratky Ctrl+Alt+Space, start služeb a připravenost v oznamovací oblasti).',
      'Plynulé skrytí do oznamovací oblasti: po dokončení inicializace mini-okno automaticky a plynule zmizí, přičemž aplikace běží připravena v tray liště pro okamžité vyvolání.',
      'Chytré potlačení na pozadí: při automatickém startu se systémem Windows v tichém režimu (--background, --silent) se splash okno nezobrazuje.',
    ],
  },
  {
    version: '1.1.9',
    date: '16. 9. 2026',
    title: 'Full-Width layout instalačního průvodce a spolehlivá instalace',
    highlights: [
      'Full-Width moderní layout instalátoru: hlavička i patička nového instalátoru jsou roztaženy přes celou šířku okna pro čistý, prémiový a vzdušný vzhled.',
      'Miniatura loga IADonkey v záhlaví: do horní lišty instalátoru byla doplněna miniatura oficiálního maskota IADonkey.',
      'Přesun odznaku instalace bez UAC: odznak „Instalace bez UAC práv“ byl přesunut z bočního panelu do levé části globální patičky okna.',
      'Bezpečné zamykání asar archivu: vyřešeno zamykání souboru resources/app.asar při instalaci náhradou monkey-patched fs za original-fs.',
      'Atomický rename-swap a bezpečné ukončení instancí: pokročilé filtrování běžících instancí zabraňuje nechtěnému pádu instalátoru.',
    ],
  },
  {
    version: '1.1.8',
    date: '16. 9. 2026',
    title: 'Vyladěný design instalátoru a oprava stability instalace',
    highlights: [
      'Větší a prostornější okno instalátoru: šířka zvětšena na 860 px a výška na 580 px pro optimální čitelnost a vzdušnost.',
      'Oficiální ikona IADonkey: v záhlaví instalátoru je umístěno oficiální logo aplikace IADonkey namísto obecné rakety.',
      'Čistý design kroků bez rušivých prvků: odstraněna vertikální propojovací čára a záře (glow) kolem aktivního kroku. Zvýšeno vertikální odsazení mezi jednotlivými kroky.',
      'Větší a lépe čitelná typografie: zvětšeny fonty názvů a popisů kroků v postranním panelu, texty informačních bublin i popisky možností instalace.',
      'Oprava pádu v kroku 3 (Instalace): vyřešeno ukončování procesů, které v předchozí verzi nechtěně zasáhlo renderer instalátoru. Instalace nyní probíhá zcela plynule od 0 do 100 %.',
    ],
  },
  {
    version: '1.1.7',
    date: '16. 9. 2026',
    title: 'Moderní 4-krokový instalátor a blesková In-App aktualizace bez prodlevy',
    highlights: [
      'Samostatný moderní instalátor (React + Tailwind): kompletní opuštění zastaralého NSIS. Nový instalátor je plnohodnotné tmavé frameless okno ve stylu aplikace s vlastním záhlavím, ikonou s fialovou září a 4 přehlednými kroky (Vítejte → Nastavení složky a zástupců → Průběh instalace → Dokončeno se zaškrtávacím polem Spustit program).',
      'Plná integrace do Windows: instalátor vytváří zástupce na Ploše a v nabídce Start přes Windows Script Host a registruje aplikaci do systémového Nastavení Windows (Přidat nebo odebrat programy) včetně čisté odinstalace.',
      'Blesková In-App aktualizace (0.5s swap): stažení i rozbalení aktualizace probíhá přímo v okně aplikace s živým tmavým progress barem a zobrazením fází. Samotná výměna souborů při restartu trvá pouze 0,5 sekundy díky okamžitému swapu – uživatel již nikdy nečeká do prázdna ani nevidí žádná bílá okna.',
      'Moderní odinstalátor: při odinstalaci přes systémové Nastavení se otevře moderní potvrzovací okno s čistým odebráním všech součástí a zástupců.',
    ],
  },
  {
    version: '1.1.6',
    date: '16. 9. 2026',
    title: '100% tichý instalátor bez systémových oken a okamžitý start aplikace',
    highlights: [
      'Úplné potlačení systémového dialogu instalátoru: instalátor má přímo ve svém jádře natvrdo nastaven tichý režim (SilentInstall silent). Ani při ručním spuštění poklepáním v Průzkumníku Windows se již nikdy nezobrazí žádné bílé systémové okno s nápisem „Instaluje se, prosím vyčkejte...“ ani zelený proužek.',
      'Okamžitý a plynulý start aplikace: po bleskovém rozbalení souborů na pozadí (cca 1 sekunda) je aplikace okamžitě spuštěna v moderním tmavém rozhraní.',
      'Bezpečné volání z aplikace: vyřešena kompatibilita při aktualizaci ze starších verzí – i pokud starší verze nespustí balíček s tichým parametrem, instalátor sám ví, že má běžet tiše a bez zobrazení oken.',
    ],
  },
  {
    version: '1.1.5',
    date: '16. 9. 2026',
    title: 'Tichá aktualizace na pozadí a moderní 1-Click instalátor bez zastaralých Win32 oken',
    highlights: [
      'Tichá aktualizace na pozadí (Silent Background Update): při kliknutí na „Restartovat a spustit novou verzi“ proběhne instalace nového sestavení během 1–2 sekund zcela tiše a neviditelně na pozadí bez jakýchkoliv systémových dialogů.',
      'Automatické spuštění nové verze: instalátor po dokončení tichého přepisu souborů aplikaci okamžitě a automaticky znovu spustí.',
      'Přechod na moderní 1-Click instalátor (oneClick): při ručním spuštění staženého instalátoru se již nezobrazuje zastaralý vícekrokový Win32 průvodce s bílými rámy a systémovými tlačítky; aplikace se nainstaluje na jedno kliknutí a ihned otevře.',
      'Čistý uživatelský zážitek: veškeré novinky a vizuální prezentace verze probíhají přímo v aplikaci IADonkey (WhatsNewModal a Spotlight) v plnohodnotném tmavém motivu.',
    ],
  },
  {
    version: '1.1.4',
    date: '16. 9. 2026',
    title: 'Kompletní vizuální redesign instalátoru Windows (NSIS) do tmavého motivu',
    highlights: [
      'Vizuální redesign instalačního průvodce Windows (NSIS): okno instalátoru nyní plně odpovídá modernímu temnému stylu aplikace IADonkey a okna Nastavení (#1E1E28).',
      'Bezešvé bitmapové podklady: uvítací i dokončovací levý panel (sidebar) a záhlaví (header) mají podklad #1E1E28, díky čemuž dokonale a plynule splývají s plochou okna bez jakýchkoliv rušivých švů.',
      'Zaoblená karta s ikonou a ambientní záře: na bočním panelu i v záhlaví je ikona IADonkey zasazena do elegantní zaoblené karty s měkkou indigo září (#6366F1) a akcentním žebrem.',
      'Tmavé ladění dialogů a ovládacích prvků: výběr cílové složky i ukazatel průběhu instalace jsou stylizovány do tmavého motivu s indigo progress barem.',
      'Odstranění rušivých dělících linek: skryty klasické šedé horizontální linky a sjednocen vzhled klientské plochy i brandingového textu.',
    ],
  },
  {
    version: '1.1.3',
    date: '16. 9. 2026',
    title: 'Vlastní snippety, import/export, katalog Material Symbols, plynulá synchronizace a vyladění UI',
    highlights: [
      'Nová záložka Snippety v Nastavení: přehledná centrální správa textových zkratek s rozdělením na Vlastní snippety a Předdefinované osobní údaje.',
      'Vlastní snippety: možnost vytvářet libovolné textové šablony s výběrem ikony z Material Symbols, víceřádkovým textem pro rychlé zkopírování do schránky a flexibilními zkratkami (:zkratka) přes štítky.',
      'Export a import vlastních snippetů: možnost zálohovat i nahrát snippety v přenosném formátu JSON přímo z nového panelu akcí bez závislosti na externích souborech.',
      'Nové předdefinované osobní údaje: přidána pole Moje Jméno (:jmeno), Moje DIČ (:dic) a Můj E-mail (:email) se sjednoceným názvoslovím v Nastavení i Spotlightu.',
      'Vylepšený katalog Material Symbols: nová komponenta IconPickerInput pro pohodlný výběr ikon ve všech formulářích s inteligentním relevančním vyhledáváním a deduplikací.',
      'Správa online katalogu ikon přesunuta na konec záložky Zdroje dat do nové sekce Externí nástroje se sjednoceným vizuálním stylem.',
      'Plynulý stav synchronizace ve Zdrojích dat s minimální dobou trvání 2 sekundy a živým progress barem namísto náhlého probliknutí.',
      'Podpora číselných dotazů MLogu již od 3 číslic (např. 123 nabídne T123 a R123).',
      'Podpora elementů <Alias> v konfiguraci MagicGate XML se stejnými možnostmi a funkcemi jako <App>.',
      'Tlačítka „Procházet...“ nyní otevírají souborový průzkumník přímo ve stávající zadané cestě nebo její nadřazené složce.',
      'Podpoložky (Alt+Enter) ve Spotlightu se nyní vždy vykreslují ve vybrané primární barvě motivu z Nastavení, z rozšíření se přebírá pouze štítek.',
      'Ochrana před kolizí globální zkratky s rezervovanými klávesovými zkratkami aplikace.',
      'Automatické resetování posuvníku na začátek při přepínání záložek v Nastavení.',
      'Kompaktní tlačítka automatické detekce cest (VS Code a Android Studio) s ikonou hvězdiček.',
      'Odstranění duplicitního zápatí v menu Nastavení pro čistší rozvržení okna.',
      'Zpřesnění výpočtu a zobrazení součtu disjunktních položek v Kompletním seznamu a ve Zdrojích dat.',
    ],
  },
  {
    version: '1.1.2',
    date: '15. 9. 2026',
    title: 'Rozšíření Android Studio, vylepšení MLog číselných dotazů, editor statických dat a vyladění UI',
    highlights: [
      'Nové rozšíření Android Studio: podpora pro vývojové prostředí Android Studio s vyhrazenou růžovou identitou a možností automatické detekce nebo ruční volby cesty ke studio64.exe.',
      'Inteligentní volba vývojového editoru: aplikace nabízí buď VS Code, nebo Android Studio – nikdy ne obojí současně. Pro repozitáře s jazykem Kotlin nebo Java se automaticky nabízí Android Studio, pro webové projekty a MagicGate se vždy nabízí VS Code.',
      'Přímé otevření v Android Studiu z nabídky akcí (Shift+Enter) i z okna klonování repozitářů.',
      'Číselné dotazy pro MLog na 4 a více číslic (např. 2111): automatické zobrazení úkolu T (T2111) na 1. místě a požadavku R (R2111) na 2. místě včetně přepnutí do MLog režimu a dohledání odkazů v informacích položek.',
      'Sjednocení cílové složky MagicGate repozitářů do podsložky magicgate/ v rámci výchozí složky pro stahování.',
      'Okamžitý reset a zavření Spotlight vyhledávače při otevření repozitáře ve VS Code nebo v Android Studiu z okna klonování.',
      'Zachování označené položky ve Spotlight vyhledávači při návratu ze subpoložek (Alt+Enter).',
      'Zpřehlednění nabídky akcí: odstranění duplicitního tlačítka rekurzivního stahování a umístění akce Otevřít na GitHubu na konec seznamu.',
      'Vylepšený editor položek statických dat: pole Název i pole Umístění roztaženo na 100 % šířky formuláře; pole Umístění převedeno na víceřádkový editor s podporou odřádkování.',
      'Resetování posuvníku na začátek při přepínání záložek v okně Jak na zdroje dat.',
      'Sjednocení a zpřesnění nápovědy a barevného stylu dle design pravidel (dodržení sekundární barvy v modálech klonování a informačním okně).',
    ],
  },
  {
    version: '1.1.1',
    date: '14. 9. 2026',
    title: 'Rozšíření (GitHub, VS Code), systém akcí a informací, klonování repozitářů a barevný design systém',
    highlights: [
      'Nová záložka Rozšíření v Nastavení: možnost zapínat a vypínat samostatné moduly MagicGate, MLog, GitHub a VS Code (s automatickým zachováním stávající konfigurace).',
      'Integrace GitHubu: přímé načítání osobních repozitářů i organizací s vyhledáváním a výchozí ikonou GitHubu.',
      'Nový systém Akcí položek (Shift+Enter): otevření webu repozitáře, stažení/naklonování repozitáře i rekurzivní klonování včetně submodulů.',
      'Přehledné samostatné systémové okno pro klonování repozitářů s výběrem cílové složky a živým zobrazením průběhu.',
      'Výchozí složka pro klonování v nastavení GitHubu a plynulý návrat fokusu do vyhledávače po dokončení.',
      'Rozšíření Visual Studio Code (VS Code): vyhrazená integrace v Nastavení s možností nastavení cesty a automatické detekce instalace Code.exe.',
      'Blesková tichá detekce existujících repozitářů v cílové složce bez blokování uživatelského rozhraní.',
      'Nová akce Otevřít ve VS Code: pokud repozitář v cílové složce existuje, nabídne se v akcích položky (Shift+Enter) s přímým otevřením ve VS Code.',
      'Vyhrazená identita VS Code: specifická hluboká petrolejová barva rozšíření, zobrazení v Chytrých funkcích a výrazné zvýraznění v nabídce akcí.',
      'Potvrzení stažení klávesou Enter v okně klonování repozitářů (jak z GitHubu, tak z MagicGate instancí).',
      'Klonování repozitářů instance MagicGate: možnost stáhnout všechny repozitáře sekcí instance přes novou akci na Shift+Enter se živým průběhem, automatickým pojmenováním podsložek a uložením repos.json.',
      'Sjednocení barev oken klonování: stavový box, spinner, tlačítko výběru složky i tlačítko pro otevření v Průzkumníku sladěny do sekundární barvy motivu.',
      'Původní podvolby položek přejmenovány na subpoložky a přesunuty pod klávesovou zkratku Alt+Enter.',
      'Nový systém Informací (info) položek na Shift+Enter: zobrazení detailních parametrů (databáze, server, mlog požadavek, cesty, zálohy apod.) v kompaktní liště nad akcemi s možností okamžitého zkopírování hodnoty.',
      'Oprava automatického posouvání (scroll) v okně Akcí a informací při klávesové navigaci šipkami.',
      'Rychlá zkratka Ctrl+Backspace ve Spotlightu pro okamžité kompletní smazání hledaného výrazu.',
      'Rychlé prefixy git: a magicgate: (mg:) a vizuální aktivace MLog režimu ve vyhledávači.',
      'Závazná pravidla barevného systému (docs/COLOR_RULES.md): vyhrazené barvy pro rozšíření, semafor pro stavy a nová paleta 10 designových odstínů pro hlavní i sekundární barvu motivu.',
      'Zlatý/jantarový akcent pro MagicGate v detailech a čipech a samostatná barevná identita pro internetové vyhledávače.',
      'Banování položek a správa Banlistu: možnost vyřadit libovolnou položku ze synchronizace i vyhledávače a nová záložka Banlist s možností obnovení.',
      'Nový interaktivní průvodce "Jak na zdroje dat" v Nápovědě s kompletní specifikací JSON/TypeScript modelu.',
    ],
  },
  {
    version: '1.0.1',
    date: '11. 9. 2026',
    title: 'Kompletní seznam položek, vyhledávání bez diakritiky a MagicGate XML',
    highlights: [
      'Nový Kompletní seznam v nastavení: přehledné modální okno zobrazující všechny indexované položky seřazené prioritně (shodně se Spotlightem) s filtry a počítadly.',
      'Plná podpora vyhledávání bez diakritiky: psaní s háčky i bez nich (např. "prik" spolehlivě najde "Příkazový řádek") s prioritním řazením podle začátků slov.',
      'Import serverové konfigurace MagicGate z deploy XML souboru (včetně instancí a dílčích aplikací Administrace, Web, API, BO).',
      'Globální podpora zástupného symbolu {favicon} pro položky i podpoložky s automatickým stahováním a mezipamětí.',
      'Integrace vyhledávače Centrum.cz s rychlými prefixy c: a centrum:.',
      'Systémové textové snippety s prefixem : (datum, čas, guid, rok, podpis), prioritou 0 a tyrkysovými čipy zkratek.',
      'Vizuální sjednocení velikosti a perfektní vycentrování ikon v seznamu položek.',
      'Automatické obnovení fokusu vyhledávacího pole po zavření okna nastavení.',
    ],
  },
  {
    version: '0.1.7',
    date: '11. 9. 2026',
    title: 'Samostatné aktualizace, detekce a mapování JSON zdrojů',
    highlights: [
      'Samostatná záložka Aktualizace v nastavení s možností ruční kontroly nových verzí a zobrazením historie změn.',
      'Inteligentní detekce struktury JSON: automatické načtení struktury a mapování vlastních polí (název, odkaz, ikona, priorita apod.) na libovolné klíče JSONu.',
      'Možnost zadání fixní hodnoty pro všechny položky zdroje (např. jednotná ikona pro celý importovaný zdroj) s živým náhledem prvního záznamu.',
      'Rychlé kopírování URL adresy API endpointů do schránky jedním kliknutím v seznamu zdrojů.',
      'Nové přehledné zobrazení a formátování času poslední synchronizace v českém genitivu (např. 5. května 11:24:24) se zarovnáním v levém menu.',
      'Okamžité automatické ukládání všech změn v nastavení bez nutnosti potvrzovacího tlačítka v patičce.',
      'Vizuální zjemnění přepínačů, odstranění duplicitních nadpisů a optimalizace rozložení okna nastavení.',
    ],
  },
  {
    version: '0.1.6',
    date: '11. 9. 2026',
    title: 'Nativní programy Windows, Google Search a vylepšení UI',
    highlights: [
      'Vyhledávání a spouštění nainstalovaných programů Windows přímo ze Start menu (klasické i UWP/Store aplikace jako Adobe XD, Kalkulačka, Windows Terminal).',
      'Extrakce originálních plnobarevných ikon aplikací v nativním rozlišení (včetně UWP aplikací).',
      'Inteligentní řazení aplikací podle začátku jednotlivých slov (zadáním "XD" se ihned nabídne "Adobe XD").',
      'Integrace Google Search: možnost okamžitého vyhledání dotazu na Google (priorita 100 na konci seznamu) i rychlý prefix google:.',
      'Možnost zapnutí a vypnutí prohledávání programů i Google Search v záložce Obecné.',
      'Sjednocení barvy ikony API zdroje v Nastavení s aktivním motivem aplikace.',
      'Spolehlivá detekce a zobrazení záložky MagicGate i v případě, že se parametr nachází pouze ve vnořených podpoložkách.',
    ],
  },
  {
    version: '0.1.5',
    date: '10. 9. 2026',
    title: 'Integrace MLog, Gmail, nová ikona a vylepšení UI',
    highlights: [
      'Automatické zobrazení vyhledávacího pole (Spotlight) ihned při spuštění aplikace s aktivním textovým kurzorem.',
      'Nová oficiální ikona IADonkey v hlavním panelu Windows (taskbaru), systémovém panelu (tray) i v záhlaví oken.',
      'Integrace helpdesku MLog: rychlé otevírání požadavků (R123) i úkolů (T456) z vyhledávače podle nastavené Base URL v nové záložce MLog.',
      'Integrace Gmailu: zadáním libovolné e-mailové adresy se okamžitě nabídne otevření nového konceptu zprávy v Gmailu s předvyplněným příjemcem.',
      'Čistější rozhraní – odstraněna přebytečná tlačítka, kliknutím na chip s číslem verze se otevře historie změn (Changelog).',
      'Sjednocení šířky záložky MLog na 100 % plochy okna Nastavení.',
    ],
  },
  {
    version: '0.1.2',
    date: '10. 9. 2026',
    title: 'Automatické aktualizace a distribuce',
    highlights: [
      'Integrovaná kontrola nových verzí aplikace přes GitHub s automatickým stažením aktualizace.',
      'Přehledné okno s novinkami zobrazené po prvním spuštění po aktualizaci.',
      'Plně automatizovaný systém přípravy a vydávání nových verzí.',
    ],
  },
  {
    version: '0.1.1',
    date: '10. 9. 2026',
    title: 'Vlastní barvy, bezpečné zkratky a správa zdrojů',
    highlights: [
      'Možnost volby vlastní barvy aplikace v nastavení (včetně hex kódu i rychlých paletek) s živým náhledem bez nutnosti restartu.',
      'Bezpečné nahrávání klávesové zkratky – vyžadována minimálně dvojkombinace kláves, ochrana proti nechtěnému stisku jediné klávesy.',
      'Dočasné pozastavení původní zkratky během editace pole v nastavení (nedochází k nechtěnému otevření launcheru).',
      'Nové přehledné ikony pro lokální JSON soubory a tlačítko přidání souboru v nastavení.',
      'Bleskový start okna nastavení bez problikávání výchozích barev (okamžitá aplikace uživatelského motivu).',
      'Přehledná historie verzí a zobrazení novinek po aktualizaci.',
    ],
  },
  {
    version: '0.1.0',
    date: '8. 9. 2026',
    title: 'První verze launcheru IADonkey',
    highlights: [
      'Rychlé vyhledávání a spouštění aplikací, webových adres a záložek.',
      'Globální vyvolání launcheru pomocí konfigurovatelné klávesové zkratky.',
      'Import dat z lokálních JSON souborů na disku a externích API endpointů.',
      'Podpora pro tichý a bezpečný login do MagicGate (systémy IS Tour).',
      'Podpora pro vnořené podpoložky (Shift+Enter pro rozbalení, Ctrl+Enter pro rychlé spuštění první volby).',
      'Integrovaná chytrá kalkulačka a přímé otevírání URL adres.',
      'Automatická synchronizace dat na pozadí s přehledným ukazatelem průběhu.',
    ],
  },
];

/**
 * Zde se průběžně zapisují novinky pro budoucí verzi.
 * Po dokončení releasu se tyto položky přesunou přímo pod vydávanou verzi a toto pole se vyprázdní.
 */
export const UPCOMING_CHANGELOG: string[] = [];

export function getLatestRelease(): VersionEntry {
  return CHANGELOG_HISTORY[0];
}
